In [1]:
import numpy as np
np.__version__

'1.18.5'

In [2]:
A=np.arange(0,21,1)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [3]:
for i in A:
    if A[i]%2 == 0:
        print(A[i])

0
2
4
6
8
10
12
14
16
18
20


In [4]:
A[A%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
for i in A:
    if A[i]%3 == 0:
        print(A[i])

0
3
6
9
12
15
18


In [6]:
A[A%3==0]

array([ 0,  3,  6,  9, 12, 15, 18])