In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [3]:
#1.有多少學生英文成績比數學成績高?
#2.是否全班同學最高分都是國文?

In [4]:
compare = np.greater(english_score , math_score)
compare

array([False,  True,  True, False, False,  True])

In [5]:
print("there are 3 people whose english is better than math")

there are 3 people whose english is better than math


In [6]:
np.greater(chinese_score , math_score)

array([ True,  True,  True,  True,  True,  True])

In [7]:
np.greater(chinese_score , english_score)

array([ True,  True,  True,  True,  True,  True])

In [8]:
print("yes,all of their chinese score are the best")

yes,all of their chinese score are the best
